# Generated by Django 3.1.4 on 2021-01-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rec',
        ),
    ]
