# Generated by Django 3.1.4 on 2021-01-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0002_delete_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSamplesForRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vacancy_id', models.IntegerField()),
                ('user_rating', models.IntegerField()),
            ],
        ),
    ]
