# Generated by Django 3.1.4 on 2021-01-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210110_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.BooleanField(default=False)),
                ('linux', models.BooleanField(default=False)),
                ('git', models.BooleanField(default=False)),
                ('postgresql', models.BooleanField(default=False)),
                ('django', models.BooleanField(default=False)),
                ('flask', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('bash', models.BooleanField(default=False)),
                ('mysql', models.BooleanField(default=False)),
                ('oop', models.BooleanField(default=False)),
                ('docker', models.BooleanField(default=False)),
                ('mongodb', models.BooleanField(default=False)),
                ('pandas', models.BooleanField(default=False)),
                ('numpy', models.BooleanField(default=False)),
                ('jira', models.BooleanField(default=False)),
                ('kubernetes', models.BooleanField(default=False)),
                ('http', models.BooleanField(default=False)),
                ('tcp_ip', models.BooleanField(default=False)),
                ('trello', models.BooleanField(default=False)),
                ('unix', models.BooleanField(default=False)),
                ('redis', models.BooleanField(default=False)),
                ('id_vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.vacancies')),
            ],
        ),
    ]
