# Generated by Django 3.1.4 on 2021-01-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_vacancies_skills'),
        ('parser_vacancies', '0002_remove_skills_id_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='id_vacancy',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.vacancies'),
            preserve_default=False,
        ),
    ]
