# Generated by Django 3.1.4 on 2021-02-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        ('parser_vacancies', '0003_skills_id_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='id_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies'),
        ),
    ]
