# Generated by Django 3.1.4 on 2021-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0004_auto_20210207_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies_count',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(null=True, unique=True)),
                ('added_today', models.IntegerField(null=True)),
                ('total_vacancies_count', models.IntegerField(null=True)),
            ],
        ),
    ]
