# Generated by Django 3.1.4 on 2021-02-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0006_auto_20210228_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies_count',
            old_name='data',
            new_name='date',
        ),
    ]
