# Generated by Django 3.1.4 on 2021-04-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0007_auto_20210228_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies_count',
            new_name='VacanciesCount',
        ),
    ]
