# Generated by Django 3.1.4 on 2021-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0007_auto_20210228_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies_count',
            name='date',
            field=models.DateField(auto_now=True, null=True, unique=True),
        ),
    ]
