# Generated by Django 3.1.4 on 2021-02-06 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vacancy', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('salary_from', models.CharField(blank=True, max_length=100)),
                ('salary_to', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('published', models.DateTimeField(blank=True)),
                ('contains_skills', models.BooleanField(blank=True, null=True)),
                ('banned_by_users', models.ManyToManyField(related_name='banned_vacancies', to=settings.AUTH_USER_MODEL)),
                ('shown_to_users', models.ManyToManyField(related_name='shown_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
    ]
