# Generated by Django 3.1.4 on 2021-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='id_vacancy',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
