# Generated by Django 3.1.4 on 2020-12-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[(1, 'Москва'), (2, 'Санкт-Петербург')], default='Москва', max_length=100)),
                ('salary', models.IntegerField(blank=True)),
                ('experience', models.CharField(choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='Нет опыта', max_length=20)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
