# Generated by Django 3.1.4 on 2020-12-27 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blabla',
            name='area',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург')], default='Москва', max_length=100),
        ),
        migrations.AlterField(
            model_name='blabla',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
