# Generated by Django 3.1.4 on 2020-12-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201227_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blabla',
            name='user_id',
        ),
    ]
