# Generated by Django 3.1.4 on 2020-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_blabla_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blabla',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург')], default='Москва', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='Нет опыта', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
