# Generated by Django 3.1.4 on 2021-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210110_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=100, verbose_name='Укажите дополнительные технологии, с которыми у вас есть опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
    ]
