# Generated by Django 3.1.4 on 2021-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('Нет опыта', 'Нет опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 до 6 лет', 'От 3 до 6 лет'), ('Более 6 лет', 'Более 6 лет')], default='Нет опыта', max_length=20, verbose_name='Опыт работы'),
        ),
    ]
