# Generated by Django 3.1.4 on 2020-12-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201229_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='Нет опыта', max_length=20, verbose_name='опыт работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='уровень зарплаты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите дополнительные технологии, с которыми у вас есть опыт'),
        ),
    ]
