# Generated by Django 3.1.4 on 2021-01-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0002_remove_skills_id_vacancy'),
        ('users', '0007_auto_20210112_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='skills',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='parser_vacancies.skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('нет опыта', 'Нет опыта'), ('от 1 года до 3 лет', 'От 1 года до 3 лет'), ('от 3 до 6 лет', 'От 3 до 6 лет'), ('более 6 лет', 'Более 6 лет')], default='Нет опыта', max_length=20, verbose_name='Опыт работы'),
        ),
    ]
