# Generated by Django 3.1.4 on 2021-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_vacancies_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='without_salary',
            field=models.BooleanField(default=False, verbose_name='Многие работодатели не указывают уровень зп, хотели бы видеть такие вакансии?'),
        ),
    ]
