# Generated by Django 3.1.4 on 2021-01-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_without_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=100, verbose_name='Через зарятую укажите дополнительные технологии, с которыми у вас есть опыт работы.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='without_salary',
            field=models.BooleanField(choices=[(False, 'Не показывать'), (True, 'Показывать')], default=False, verbose_name='Многие работодатели не указывают уровень зп, показывать такие вакансии?'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
