# Generated by Django 3.1.4 on 2021-01-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210122_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='vacancy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.vacancies'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Больше не показывать'), (2, '2'), (3, '4'), (4, '5'), (5, '5')]),
        ),
    ]
