# Generated by Django 3.1.4 on 2021-01-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210122_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='rating',
            name='vacancy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.vacancies'),
        ),
    ]
