# Generated by Django 3.1.4 on 2021-01-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210122_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
