# Generated by Django 3.1.4 on 2021-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Больше не показывать'), (2, '2'), (3, '4'), (4, '5'), (5, '5')], null=True),
        ),
    ]
