# Generated by Django 3.1.4 on 2021-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_vacancies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='rating',
            field=models.CharField(blank=True, choices=[(1, 'Больше не показывать'), (2, '2'), (3, '4'), (4, '5'), (5, '5')], max_length=100, null=True),
        ),
    ]
