# Generated by Django 3.1.4 on 2021-01-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_vacancies_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='users',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='shown_to_users',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
