# Generated by Django 3.1.4 on 2021-01-25 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210125_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='shown_to_users',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
