# Generated by Django 3.1.4 on 2021-01-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210125_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='shown_to_users',
        ),
    ]
