# Generated by Django 3.1.4 on 2021-01-26 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_vacancies_shown_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='shown_to_users',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='shown_to_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
