# Generated by Django 3.1.4 on 2021-01-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vacancies'),
        ),
    ]
