# Generated by Django 3.1.4 on 2021-01-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rating_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
    ]
