# Generated by Django 3.1.4 on 2021-01-26 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210126_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='shown_to_users',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='shown_to_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
