# Generated by Django 3.1.4 on 2021-02-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_vacancies', '0004_auto_20210207_0052'),
        ('users', '0032_auto_20210128_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='banned_by_users',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='shown_to_users',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Vacancies',
        ),
    ]
