# Generated by Django 3.1.4 on 2020-12-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('area', models.CharField(choices=[('1', 'Москва'), ('2', 'Санкт-Петербург')], default='1', max_length=100)),
                ('experience', models.CharField(choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='noExperience', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
