# Generated by Django 3.1.4 on 2020-12-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
