# Generated by Django 3.1.4 on 2020-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_profile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='area',
            new_name='город',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='salary',
            new_name='зарплата',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='опыт',
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=30),
        ),
    ]
